### ISSUE TITLE
Failed to fetch config - Ignition failed

### ISSUE THREAD

**Issue by asak99** [coreos/ignition#1115] opened 2020-10-21 03:18 UTC
# Bug #

## RHCOS 4.6 Nightly##

Baremetal - Assisted Installation 

What hardware/cloud provider/hypervisor is being used to run Ignition?

Mount Discovery ISO image and begin install - 

Fails with message - failed to fetch ignition config, Config is not valid.

Previous 5 days Discovery ISO - 4.6 Nightly works fine on same system .
[](url)
<img width="1760" alt="ignition" src="https://user-images.githubusercontent.com/48545811/96669296-ca0aa880-1311-11eb-8ae5-3f1eab8b77b6.png">

**Comment by asak99** [comment] 2020-10-21 03:20
[
<img width="1760" alt="ignition" src="https://user-images.githubusercontent.com/48545811/96669247-b52e1500-1311-11eb-9438-1991a18a82a3.png">
](url)

**Comment by bgilbert** [comment] 2020-10-21 03:27
Is there a newline in the middle of a string literal on line 12 of your Ignition config?

**Comment by asak99** [comment] 2020-10-21 03:30
I havent checked any ignition config file, As mentioned in Assisted installation , i downloaded discovery iso image and mounted as virtual CD and booted, Observed this error.

**Comment by bgilbert** [comment] 2020-10-21 03:38
It seems likely that the problem is with the Ignition config, not with Ignition itself.  I'll close this, but please feel free to reopen if you find evidence that Ignition is behaving improperly.  I'd recommend reporting your issue through OpenShift support channels, or to the assisted-installer component of the OpenShift Container Platform in [Red Hat Bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Container%20Platform).

**Closed by bgilbert** 2020-10-21 03:38 UTC
