### ISSUE TITLE
different Live USB boot results with unclear error messages

### ISSUE THREAD

**Issue by pjvleeuwen** [coreos/ignition#1144] opened 2020-12-06 11:49 UTC
Since I am a new FCOS user I might have a nice uninformed perspective. Via some tickets I will share some problems I ran into, in the hope that others might find them and be helped by it.

Purpose for this ticket is to address the helpfulness of the error messages. Maybe this can be improved or prevented in this project? I will also file under the documentation project as we might also improve there.

When burning to a USB stick I get different response based on how I burn it:

Attempt 1:

* when burning "fedora-coreos-32.2020**1104**.3.0-live.x86_64.iso" with **tuxboot**-0.8.3.exe
* and booting in BIOS mode the booting halts with the message "no configuration file"
* when I provide the IGN filename it results in the messsage "booting kernel failed: invalid argument"
* it seems that the configuration file it is missing is an SYSLINUX CFG file
* trying all CFG files on the stick, like "EFI/fedora/grub.cfg", result in "failed to load COM32 file EFI/fedora/grub.cfg.c32"

Attempt 2:

* when burning "fedora-coreos-32.2020**1018**.3.0-live.x86_64.iso" with **tuxboot**-0.8.3.exe
* it fails while burning at the action "Running special E:\utils\win32\syslinux.exe on E:" which prompts Windows dialog "This file does not have an app associated with it..."

Attempt 3:

* when burning "fedora-coreos-32.2020**1018**.3.0-live.x86_64.iso" with **rufus**-3.13p.exe in "**ISO** Image mode"
* and booting in either BIOS or UEFI mode the CoreOS splash-screen comes by, but booting fails with message "failed to mount /run/media/iso"

Since this at least starts the CoreOS, so this suggests that `rufus` is a better  alternative for `tuxboot` here!
Earlier problems with Ubuntu Live USB in the past made me switch from unetbootin to tuxboot based on the Ubuntu documentation.
It might be worth to document a 'known working setup' for FCOS in the documentation as apparently YMMV.

Attempt 4:

* when burning "fedora-coreos-32.2020**1018**.3.0-live.x86_64.iso" with **rufus**-3.13p.exe in "**DD** Image mode"
* and booting in the only available mode (unclear which it is) the CoreOS bash prompt comes up as expected

As we can see this took a lot of trial and error and the error messages above were not very helpful. This is not a nice first experience with FCOS, so it would be nice if this experience could be improved somehow.

**Comment by bgilbert** [comment] 2020-12-06 18:20
Thanks for reporting.  This is a docs issue, not an Ignition issue, so I'll close as a duplicate of https://github.com/coreos/fedora-coreos-docs/issues/213.

**Closed by bgilbert** 2020-12-06 18:20 UTC
Labels: area/usability, kind/question
