### ISSUE TITLE
Enable config-drive by default

### ISSUE THREAD

**Issue by hardys** [coreos/ignition#769] opened 2019-03-21 16:08 UTC
# Feature Request #

When deploying nodes, you don't always have a location to host the ignition config, or a way to modify the deployed image, and in these cases it's very helpful to allow injection of the config using a config drive/partition.

There is support for this in the openstack and cloudstack provider already, where any device with the config-2 label can be used to provide the config.

I wanted to have a discussion about enabling this by default, since this could be a pretty low-overhead addition (we'd simply skip if the disk doesn't exist), and could be checked after all existing default providers?

The specific motivation is we'd like to use some coreos images which are built for baremetal deployments, but deploy with a provisioning tool (metalkube/OpenStack Ironic) that can't easily modify the disk image (e.g the kernel cmdline), or host the ignition config, but it can easily write an additional config partition.

**Comment by bgilbert** [comment] 2019-03-21 17:07
The fundamental problem with config drives is that they have an unfixable race condition.

1. There is no way to know when storage devices have finished enumerating.  If we don't find a config drive, it's possible that it just hasn't showed up yet.  This is especially relevant on systems with a large number of storage devices.
1. Conversely, the user is not required to supply a config drive, so we can't wait forever for one to appear.

In practice, this means we (either Ignition or the underlying systemd units) need to implement a timeout waiting for the config drive.  That causes problems:

1. If we time out too early, we will ignore the user's Ignition config and continue booting.  A fundamental principle of Ignition is that it should not appear to succeed, and thus allow the system to continue booting, when in fact it has failed.
1. If we set a very long timeout, and the user does not provide a config drive, the first boot will be delayed for a long time.

So far, we've chosen to support config drives on platforms where it's absolutely unavoidable, but we've heavily discouraged the practice.  We'd prefer that platforms provide userdata support in a race-free way, via explicit hypervisor support or a network metadata service.

For OpenStack in particular: we do support its metadata service.  Is that not an option for you?

**Comment by hardys** [comment] 2019-03-21 17:17
@bgilbert thanks for the feedback - to clarify the metadata service is not an option in this case, because we're using standalone Ironic (no Nova metadata service) via metalkube: https://github.com/metalkube/

In our specific case we provide a config drive which contains the igntion config, which ends up on the same disk as the OS, thus no race condition, but I do see your point where multiple devices are involved.

We may have to look at hosting the ignition config on a webserver somewhere, but we still have the issue that we'd have to inject the URL into the image and we're trying to avoid modifying the image prior to deployment.

Maybe we can fake the metadata service via iptables or something instead.

cc @derekhiggins

**Comment by bgilbert** [comment] 2019-03-21 17:31
To clarify, you can write a config partition but not modify an existing partition?  It's also possible to write a `config.ign` file to the OEM partition on Container Linux.  We'll support equivalent functionality (in a different location) on Fedora CoreOS and Red Hat CoreOS.

**Comment by hardys** [comment] 2019-03-21 20:33
@bgilbert Yes, Ironic provides the facility to write a config partition, but not to modify the OS image that it deploys - IIRC we already looked at the OEM partition option, but the same problem exists where we can't modify the kernel cmdline in the OS image prior to firstboot. @derekhiggins and @juliakreger can probably provide more info on exactly what we tested there.

If you can provide any more information re what interfaces we can expect for the equivalent functionality in RHCOS that would be a great help, thanks!

**Comment by juliakreger** [comment] 2019-03-21 21:50
I'm a little confused regarding the mention of the OEM partition option as I understood it to be a feature that was being removed based upon some of the dracut start changes for ignition. Additionally, in the RHCOS images I have looked at, there is no OEM partition and the statement of eventual support is slightly concerning given the the need that is trying to be addressed. I'd highly prefer that we avoid trying to attach a fake metadata service to the network as there is no guarantee that the deploy-er is the owner/manager of the entire physical broadcast domain of the network.

Anyway, for machines written using ironic (Which would include services like Rackspace's metal option (although, they changed the constant for the partition name...)), the config-2 partition is actually added to the existing primary partition table and the table is then repaired for the inevitably larger disk, if applicable with GPT. As such, there shouldn't really be a chance of a race condition as a result as there is no sort of separate disk device being handled or enumerated for the location of the configuration drive contents beyond what has already been loaded to initiate the boot of the system upon boot. In other words, if the root disk is visible, the configuration drive should be present, and if not present can be skipped because it simply does not exist otherwise. In the hypervisor case, I totally see the argument of a race being a concern as they are typically treated as a virtual CD device attached to the disk bus at that point.

**Comment by ajeddeloh** [comment] 2019-03-21 23:12
Why not just use the `openstack` platform id?

**Comment by bgilbert** [comment] 2019-03-21 23:24
@hardys Modifying the kernel command line isn't necessary.  The distro will read a `config.ign` file from a well-known path in an existing partition.  If Ironic can't write files into existing filesystems, of course, that won't work here.

@juliakreger I phrased that unclearly.  We're not planning to replicate the OEM partition for FCOS or RHCOS; we're planning to read the `config.ign` from somewhere else, probably `/boot`.

I hadn't thought about a config partition on the boot drive itself.  It appears to (mostly) solve the race condition, but I'm not sure we'd want to encourage platforms to inject partitions into the OS image.  At least for now, I'd prefer to support such functionality only on platforms that specifically need it.

Does Ignition not correctly detect the Ironic config drive with the platform set to `openstack`?

**Comment by hardys** [comment] 2019-03-22 13:37
Thanks for all the feedback, to clarify we're currently testing with a modified version of the RHCOS openstack image, but we'd like to switch to use the BIOS/UEFI baremetal images, since we need some things like dhcp on all interfaces, and predictable interface naming, that are common to all baremetal deployments (and, we'd like to align with the more general RHCOS baremetal story).

Re setting the platform to openstack - perhaps I'm missing something, but how can we do that if Ironic can't modify the RHCOS disk image, and ignition in that image won't by default read the config-drive partition that's labelled config-2?  Sounds like a chicken/egg problem but perhaps there's something I've not yet considered :)

It sounds like we're close to alignment, e.g if you have plans to read config.ign from /boot, we'd just need some way to check an additional partition instead - we don't necessarily care about the OpenStack user/meta-data format for this use-case, we just need a way to reliably and securely provide the first-boot ignition config for baremetal deployments.

Thanks for any further ideas you can provide! :)

**Comment by lucab** [comment] 2019-03-22 16:10
Surfacing from a private conversation: IPMI has a FRU storage ares for "customer definable"  data under the "Product Info Area" and a freeform OEM record type (ref: https://www.intel.com/content/www/us/en/servers/ipmi/information-storage-definition-rev-1-2.html), which could be used for pre-provisioning the userdata, eliminating the need to manipulate the OS image.
However:
 * the available space depends on the specific storage chip, and it likely too small for any reasonable use (spec has >=70 bytes, but likely most of the chips are at the lower limit)
 * OS may need to authenticate to the IPMI interface, and we have a credentials bootstrapping problem

**Comment by bgilbert** [comment] 2019-03-22 22:55
The purpose of the OpenStack image is that it's properly configured to work on OpenStack.  Preferably we can get that same image working on both nova and ironic.  If that's impossible, we could perhaps have a different image for each sub-platform.  But platforms with specific extra requirements should really use a platform-specific ID and image, not `metal`.

> we need some things like dhcp on all interfaces and predictable interface naming

AFAIK those shouldn't be specific to the bare-metal image.

> Re setting the platform to openstack - perhaps I'm missing something, but how can we do that if Ironic can't modify the RHCOS disk image, and ignition in that image won't by default read the config-drive partition that's labelled config-2?

Right, I didn't intend to propose that you override the platform ID.  My question was whether Ignition was correctly reading the config drive when booted from an `openstack` image.

**Comment by juliakreger** [comment] 2019-03-23 01:01
> The purpose of the OpenStack image is that it's properly configured to work on OpenStack. Preferably we can get that same image working on both nova and ironic. If that's impossible, we could perhaps have a different image for each sub-platform. But platforms with specific extra requirements should really use a platform-specific ID and image, not `metal`.
> 

I think we've got some disconnects, so I'll try and share my context.

Many (including organizations and long standing OpenStack contributors) express a context that OpenStack is virtualization, when it as a whole is an IaaS platform with numerous possible backends. For compute resources, that means that typically is the context of nova, but nova is just an API service with multiple different backends which can vast differences. If a virtual machine, the hypervisor could be qemu, hyperv, xen, zvm, vmware, powervm. Nova is able to treat bare metal resources via ironic as just another "hypervisor". In the case of many of those "hypervisors", ironic included... instances may be BIOS booted or UEFI booted based upon user request or hardware constraints  Granted, BIOS is never going to disappear for virtual machines, but for bare metal we've been seeing vendors ship hardware that only UEFI boots for several years (in more limited, but growing cases as the expected EOL for BIOS emulation support in a particular brand of processors is ?2020?).

I think at the same time, there is a perception that metal images are the only supported image for operating on bare metal hosts and possibly contains different settings and drivers

> > we need some things like dhcp on all interfaces and predictable interface naming
> 
> AFAIK those shouldn't be specific to the bare-metal image.

As far as I understand, the image intended for openstack seems to expect and operate DHCP on only the first ethernet interface. I guess somewhere there is an assumption that OpenStack only offers a single network interface? Or maybe it is a hold over from other platforms. *shrugs* Granted, I've personally not dissected the image to verify that behavior. I've only dissected images to verify bios boot or uefi boot.

> > Re setting the platform to openstack - perhaps I'm missing something, but how can we do that if Ironic can't modify the RHCOS disk image, and ignition in that image won't by default read the config-drive partition that's labelled config-2?
> 
> Right, I didn't intend to propose that you override the platform ID. My question was whether Ignition was correctly reading the config drive when booted from an `openstack` image.

Ignition does correctly read the config drive when the OpenStack image is deployed via ironic, however those images (as of the last time I dissected them about a week ago), were BIOS booting only.  Ultimately UEFI + OpenStack will be needed not just for bare metal, but also for users and operators that need a higher level of security assurance needs where features like system attestation and measurement via the TPM are required.

**Comment by cgwalters** [comment] 2019-03-24 22:21
>  the config-2 partition is actually added to the existing primary partition table and the table is then repaired for the inevitably larger disk, if applicable with GPT

I understand that this approach has been working for Ironic so far, but would it be feasible to implement the "inject Ignition as `config.ign` into partition labeled `boot`"?  It's a very generic and easy to understand mechanism applicable to a variety of cases.  It's pretty easy to do with e.g. `guestfish` or just direct Linux `mount`.

Implementing the logic for `config-2` - if on same drive as boot - in Ignition seems doable though too.

**Comment by bgilbert** [comment] 2019-03-24 23:43
@juliakreger Okay, got it.  I had understood ironic as a separate service from nova, not as a backend of nova.

I think you're seeing a couple artifacts of the current implementation:

- initramfs networking in FCOS/RHCOS is pretty hacky at the moment, based on functionality already available in dracut.  If it's only DHCPing on the first interface, that's a bug we should fix.
- While we currently have separate BIOS and UEFI images, that's not what we want to do in the long run (https://github.com/coreos/coreos-assembler/issues/334).  CoreOS Container Linux has long had unified images, in part for the reasons you mentioned.

For both FCOS and RHCOS, every platform image will contain exactly the same bits, including drivers.  The only difference will be the platform flag itself, which will activate some conditionals in Ignition, coreos-metadata, systemd units, udev rules, etc.  And there are other *COS platforms besides `openstack` that will explicitly support bare metal, e.g. Packet is entirely a bare-metal provider and AWS has bare-metal instance types.

> Ignition does correctly read the config drive when the OpenStack image is deployed via ironic

In that case, Ignition itself is working as intended.  If the FCOS and RHCOS `openstack` images don't meet your needs, we should either fix them or add additional `openstack` images that do.

**Comment by cgwalters** [comment] 2019-03-25 14:32
Is this the code in question? https://github.com/openstack/ironic/blob/e12804ab63d12885e19d60e9afad03cff126dee2/ironic/drivers/modules/ansible/playbooks/roles/deploy/files/partition_configdrive.sh#L55

**Comment by juliakreger** [comment] 2019-03-25 16:32
> I understand that this approach has been working for Ironic so far, but would it be feasible to implement the "inject Ignition as `config.ign` into partition labeled `boot`"? It's a very generic and easy to understand mechanism applicable to a variety of cases. It's pretty easy to do with e.g. `guestfish` or just direct Linux `mount`.

@cgwalters  We've historically operated with the tenant of minimal modification of image contents and a similar discussion for the OEM partition was semi-rejected already by the community as it would require highly specific code paths. This in favor of more generic multi-platform friendly paths.

Then again, in the grand scheme of the universe with this discussion, maybe there would be willingness in the ironic community to have explicit support for ignition as the generic mechanisms seem like they are not going to really play nicely with ignition at present. I'll at least raise it again in the ironic community.

**Comment by juliakreger** [comment] 2019-03-25 16:40
> Is this the code in question? https://github.com/openstack/ironic/blob/e12804ab63d12885e19d60e9afad03cff126dee2/ironic/drivers/modules/ansible/playbooks/roles/deploy/files/partition_configdrive.sh#L55

Not the present code path. We have four different plugin based deployment interfaces that can be defined per baremetal node to choose the path as it were. The ansible one is much more geared towards highly specific tuning where as the most of our usage ideally takes the path of the direct interface. https://review.openstack.org/#/q/topic:feature/ironic-ignition was kind of what I was hacking on a while back for OEM partitions which would have tied into our most commonly used and tested deployment interfaces "iscsi" and "direct".

**Comment by cgwalters** [comment] 2019-03-25 16:45
> In that case, Ignition itself is working as intended. If the FCOS and RHCOS openstack images don't meet your needs, we should either fix them or add additional openstack images that do.

Agreed with this!  And sorry, I had totally missed the fact that Ignition *does* implement `config-2` today.

So...short term, do we need to add `openstack-metal-uefi`?  

Today you're right that the `openstack` image hardcodes `eth0`.  This is related to https://github.com/openshift/os/issues/378 and https://github.com/coreos/coreos-assembler/issues/406 - I think we can take a spike at investigating that soon which should help.

However...in practice it seems to me that Ironic has the same need to do network config that other bare metal cases do - see https://github.com/coreos/coreos-installer/pull/18

**Comment by derekhiggins** [comment] 2019-03-25 16:59
> * initramfs networking in FCOS/RHCOS is pretty hacky at the moment, based on functionality already available in dracut.  If it's only DHCPing on the first interface, that's a bug we should fix.

Just to confirm, this is the behaviour that caused us to need to customise the openstack image, we are adding " ip=eth1:dhcp" to the kernel command line so that it does dhcp from both eth0 and eth1, removing that need would mean we don't have to patch the image before we can use it.

The only other customisation we are doing on the image is to resize the disk image to reduce it, but this is only do reduce deploy times.

**Comment by bgilbert** [comment] 2019-03-25 17:02
> The only other customisation we are doing on the image is to resize the disk image to reduce it, but this is only do reduce deploy times.

Side note on precedent: Container Linux ships an `openstack` image and a smaller `openstack_mini` image.

**Comment by juliakreger** [comment] 2019-03-25 17:07
> > The only other customisation we are doing on the image is to resize the disk image to reduce it, but this is only do reduce deploy times.
> 

Are we just removing whitespace out of the qcow2 or or we doing more?

**Comment by cgwalters** [comment] 2019-03-25 17:09
> Just to confirm, this is the behaviour that caused us to need to customise the openstack image, we are adding " ip=eth1:dhcp" to the kernel command line so that it does dhcp from both eth0 and eth1, removing that need would mean we don't have to patch the image before we can use it.

OK cool, I think we should be able to fix that by this week.

**Comment by derekhiggins** [comment] 2019-03-25 17:14
> > > The only other customisation we are doing on the image is to resize the disk image to reduce it, but this is only do reduce deploy times.
> 
> Are we just removing whitespace out of the qcow2 or or we doing more?

We are remove whitespace, to be specific, the disk image size of the RHCOS image is 16G but only contains 2 filesystems (3G and 300M) so we are reducing the disk size so about 4G has to be written to disk instead of 16G. On a virt environment where were are doing it on 3 VM's in parallel it makes a big difference. 
https://github.com/openshift-metalkube/dev-scripts/commit/5f9efe861e9e443ff1bebda26f4c21bfd585d4f5

**Comment by cgwalters** [comment] 2019-03-25 17:28
> so we are reducing the disk size so about 4G has to be written to disk instead of 16G.

See also https://github.com/coreos/coreos-assembler/pull/332

**Comment by cgwalters** [comment] 2019-03-25 23:14
One thing I want to emphasize is that "the iron is still hot" so to speak for the RHCOS `openstack` image - we can make it do whatever we want to do that helps OpenStack.  IMO it's easy and fun to hack on *COS systems via [coreos-assembler](https://github.com/coreos/coreos-assembler) - rather than treating the output as something we need to postprocess downstream.

**Comment by imain** [comment] 2019-03-26 17:07
> > Just to confirm, this is the behaviour that caused us to need to customise the openstack image, we are adding " ip=eth1:dhcp" to the kernel command line so that it does dhcp from both eth0 and eth1, removing that need would mean we don't have to patch the image before we can use it.
> 
> OK cool, I think we should be able to fix that by this week.

Cool!  Can you ping me when that's ready and I'll take a look at it?  We're wanting to get this figured out asap.  :)  Thanks guys!!

**Comment by cgwalters** [comment] 2019-03-27 13:27
Just updated https://github.com/coreos/coreos-assembler/pull/332 which will shrink the FCOS metal disk to ~`2.6GB` today and RHCOS to `2.9GB`.

**Comment by cgwalters** [comment] 2019-03-27 21:25
(I know this is the Ignition issue tracker but this one morphed into "General OpenStack + *COS issues" so...)

https://github.com/coreos/coreos-assembler/pull/442 will address the DHCP issue.

**Comment by derekhiggins** [comment] 2019-03-29 16:36
> Just updated [coreos/coreos-assembler#332](https://github.com/coreos/coreos-assembler/pull/332) which will shrink the FCOS metal disk to ~`2.6GB` today and RHCOS to `2.9GB`.

> coreos/coreos-assembler#442 will address the DHCP issue.


thanks, I'll see if I can move us unto the newer images early next week

**Comment by ajeddeloh** [comment] 2019-04-11 20:26
So it sounds like we're all in agreement that this isn't an Ignition bug, but rather a question of what platform id to use and other configuration questions. I'm going to close this out since its not really a bug, but feel free to continue having conversation here. Also feel free to reopen if I'm misunderstanding.

**Closed by ajeddeloh** 2019-04-11 20:26 UTC
Labels: area/usability, kind/enhancement
