### ISSUE TITLE
No network (IPv4?) connectivity via Ethernet at first boot for LUKS/Clevis setup

### ISSUE THREAD

**Issue by rugk** [coreos/ignition#1201] opened 2021-04-30 20:49 UTC
# Bug #

## Operating System Version ##

Fedora CoreOS 33

## Ignition Version ##

Don’t know. What’s included in fedora-coreos-33.20210328.

## Environment ##

Bare metal. fedora-coreos-33.20210328

## What I did ##

Use a YAML to wipe and [encrypt the root partition / and expand it e.g.](https://docs.fedoraproject.org/en-US/fedora-coreos/storage/#_sizing_the_root_partition) and setup the encryption via clevis with a tang server:

```yaml
variant: fcos
version: 1.3.0
# ...
luks:
    # encrypted root
    - name: root
      label: luks-root
      device: /dev/disk/by-partlabel/root
      clevis:
        tpm2: false
        threshold: 1
        tang:
          - url: # ...
            thumbprint: # ..
      wipe_volume: true
```

Just installed it directly to the boot disk:
```
$ sudo coreos-installer install /dev/sdd -i ignition/[…].ign --image-file downloads/fedora-coreos-33.20210328.3.0-metal.x86_64.raw.xz --delete-karg 'console=ttyS0,115200n8'
```

And booted.

## Actual Behavior ##

Now, however, when booting it all works fine until Clevis tries to contact the Tang server for the encryption key for LUKS.
Strangely I get an network error.

Ignition reports STDERR output for `clevis luks bind -f  -k /somekeyfile/root -d “…/by-partlabel/root” “sss” “some-json”`:
> Unable to fetch advertisement: [url] 
> Invalid input!

It also [reports one more warning](https://github.com/coreos/ignition/issues/1192), which is likely not related though and clearly a bug or so.

## Expected Behavior ##

LUKS/Clevis should be able to fetch the config from the network and at least Ethernet configuration should work… 

## Troubleshooting

Actually, in the emergency shell I discovered that I cannot `curl` to any URL or so, so it clearly has no networking.

The device is connected via an Ethernet cable, so that should™ work. Additionally, I should say **when using the “live system”**, i.e. just booting from an USB with the default ignition file, **it actually also does work**. There, I can also use `nmcli` etc., but this does not work in the emergency shell apparently…

So I just used `ip` and it indeed shows (only) IPv6 adresses hmm… :thinking: 
Note my Tang server URL is an IPv4 address.

![coreos-no-network|690x348](https://aws1.discourse-cdn.com/business4/uploads/fedoraproject/original/2X/7/79e3a9da220273c60fd5f30914292bf332c1583a.jpeg) 

(Sorry for the image I tried to mount an attached USB drive, but could not find the correct `/dev/…` device, at least there was no `/dev/sd*`.)

Also note the LEDs at the network adapter look well (yellow top left is constantly on; green top right is slowly blinking at regular intervals).

---

Also asked in the Fedora forum: https://discussion.fedoraproject.org/t/no-network-ipv4-connectivity-via-ethernet-at-first-boot-for-luks-clevis-setup/29260?u=rugk

**Comment by bgilbert** [comment] 2021-04-30 23:33
As far as Ignition is concerned, this looks like a duplicate of #1163.  Starting with Ignition 2.10.0, Ignition should wait indefinitely for the Tang server to be available.  Ignition 2.10.0 should be included in the next FCOS `testing` release.  If Ignition doesn't wait for the network in that release, please open a new bug.  I'll close this; thanks for reporting.

As for why you don't have networking in the initramfs... that's another question.  I'd suggest starting by checking for NetworkManager journal entries.

**Closed by bgilbert** 2021-04-30 23:33 UTC

**Comment by rugk** [comment] 2021-05-02 18:15
Okay tried it with `fedora-coreos-33.20210426.2.0-metal.x86_64.raw.xz` and I get the same error.

> Starting with Ignition 2.10.0, Ignition should wait indefinitely for the Tang server to be available. […] If Ignition doesn't wait for the network in that release, please open a new bug.

Uhm and how can I see that?
I mean it should run into some timeout, should not it?

I just get the exact same error, here. There is also no step before clevis that seems to check that the server is there, because that would have failed.

---

Oh, but oh, I just saw I used the wrong URL: It was not `http://tang-server-ip:tang-server-port`, but `http://tang-server-ip:tang-server-port/adv`, which resulted 

As such the URL it shows me and builds is `http://tang-server-ip:tang-server-port/adv/adv/some-hash-here`, which it of course cannot contact.

**Comment by rugk** [comment] 2021-05-02 18:36
However, cURL still fails and `ip a` is very clear it has nop connection. Anyway, I'll better continue this discussion at [the forum](https://discussion.fedoraproject.org/t/no-network-ipv4-connectivity-via-ethernet-at-first-boot-for-luks-clevis-setup/29260?u=rugk). Thanks for your help in any case.

**Comment by bgilbert** [comment] 2021-05-03 16:43
> I just get the exact same error, here. There is also no step before clevis that seems to check that the server is there, because that would have failed.

As I said, the fix won't be available until the next `testing` release.

**Comment by rugk** [comment] 2021-05-03 17:47
… ah “next”, I totally overread that, sorry.
