### ISSUE TITLE
Failure adding a user that is a member of the "users" group.

### ISSUE THREAD

**Issue by arizvisa** [coreos/ignition#1601] opened 2023-04-09 20:58 UTC
# Bug #
It appears you can't use the "users" group within `passwd.users` because it doesn't exist, or within `passwd.groups` because the group already exists. I assume that this part of ignition is not idempotent.

```
{"ignition":{"version":"3.3.0"},"passwd":{"users":[{"groups":["users"],"name":"core","noUserGroup":true,"passwordHash":"$1$$PsuPeH6mHmKdRxC/yQ6a0.","primaryGroup":"wheel","shell":"/bin/bash","shouldExist":true}]}}
```

Emits: 
```
CRITICAL : ignition failed: failed to create users/groups: failed to configure users: failed to create user "core": exist status 6: Cmd: "useradd" "--root" "/sysroot" "--create-home" "--no-user-group" "--password" "$1$$PsuPeH6mHmKdRxC/yQ6a0." "--comment" "CoreOS Admin" "--gid" "wheel" "--groups" "adm,sudo,systemd-journal,wheel,users" "--shell" "/bin/bash" "core" Stdout: "" Stderr: "useradd: group 'users' does not exist
"
```

Whereas:
```
{"ignition":{"version":"3.3.0"},"passwd":{"groups":[{"name":"users"}],"users":[{"groups":["users"],"name":"core","noUserGroup":true,"passwordHash":"$1$$PsuPeH6mHmKdRxC/yQ6a0.","primaryGroup":"wheel","shell":"/bin/bash","shouldExist":true}]}}
```

Emits:
```
CRITICAL : Ignition failed: failed to create users/groups: failed to configure groups: failed to create group "users": exist status 9: Cmd: "groupadd" "--root" "/sysroot" "--password" "*" "users" Stdout: "" Stderr: "groupadd: group 'users' already exists
"
```

## Operating System Version ##
CoreOS 37.20230218.3.0 (1 month old, most recent is v37.20230322.3.0)

## Ignition Version ##
2.14.0, (most recent is v2.15.0)

## Environment ##

What hardware/cloud provider/hypervisor is being used to run Ignition?
VMware ESXi

## Expected Behavior ##
Should create the "core" user as a member of the "users" group.

## Actual Behavior ##
Ignition failure.

## Reproduction Steps ##
Please review "Bug" section.

**Comment by bgilbert** [comment] 2023-04-09 22:07
Thanks for the report.  This a duplicate of #1596.

**Closed by bgilbert** 2023-04-09 22:07 UTC
