### ISSUE TITLE
Add storage: volatile: true

### ISSUE THREAD

**Issue by cgwalters** [coreos/ignition#935] opened 2020-03-16 13:36 UTC
Let's support something like:

```
storage:
  volatile: true
```

This would have an effect like passing the `systemd.volatile` kernel command line argument; see also https://github.com/ostreedev/ostree/pull/856

Basically we have this logic today in our "Live" path; this would generalize it so it could easily be used for cloud instances too.

In particuar, I can see this being used by openshift-install for the bootstrap node.  Then we could pretty easily get rid of the bootstrap node requirement and have it re-Ignition itself into a control plane node.  This would *greatly* help the baremetal provisioning flow which does weird things with running bootstrap in a VM.

**Comment by cgwalters** [comment] 2020-03-16 16:07
The implementation of this could just be writing out `/run/ostree-live`, and then we teach [fedora-coreos-config](https://github.com/coreos/fedora-coreos-config) how to handle that generically.  Or we could try to get agreement with systemd upstream to have `/run/systemd.volatile` or something that other Ignition users could also key off of.

**Comment by cgwalters** [comment] 2020-03-17 19:00
@bgilbert raised in chat the issue of how this interacts with rebooting.  I think the basic answer here is - we wouldn't remove the `/boot/ignition.firstboot` flag, the same way we don't in the liveOS path.  So every boot would run Ignition.

**Comment by darkmuggle** [comment] 2020-03-19 03:26
> The implementation of this could just be writing out `/run/ostree-live`, and then we teach [fedora-coreos-config](https://github.com/coreos/fedora-coreos-config) how to handle that generically. Or we could try to get an agreement with systemd upstream to have `/run/systemd.volatile` or something that other Ignition users could also key off of.

I'm not sure that we can use `systemd.volatile=yes`, since it only remounts `/sysroot`.  I think that the caused by `systemd-tmpfiles` but not sure.

``` 
bash-5.0# pwd
/sysroot/ostree/deploy/fedora-coreos/var/home
bash-5.0# find .
.
./core
./core/.bash_logout
./core/.bash_profile
./core/.bashrc
bash-5.0# find /home
/home
```

**Comment by cgwalters** [comment] 2020-03-19 15:05
> I'm not sure that we can use systemd.volatile=yes

Agreed; a lot of the upstream systemd stuff is oriented towards mounting `/usr` as a filesystem, kind of glossing over how `/` is managed.  OSTree is much stricter with its `/etc` and `/var` are the only writable bits model.

**Comment by bgilbert** [comment] 2020-11-05 21:32
This is a very OS-specific option, which mitigates against the feature, and it seems like this functionality could be implemented with kargs support (#1051) and/or writing a normal file.  Closing for now.

**Closed by bgilbert** 2020-11-05 21:32 UTC
Labels: jira

**Comment by cgwalters** [comment] 2020-11-19 18:30
Moved this to https://github.com/coreos/fedora-coreos-tracker/issues/674
